language: php

env:
  - SYMFONY_VERSION=2.2.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --dev

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
